image: debian:stable

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

cache:
  paths:
    - cgd/
    - werc/

before_script:
  - apt update
  - apt install -y wget 9base procps

  - export CGD=$(realpath ./cgd/bin/cgd)
  - export WERC=$(realpath ./werc)
  - export PLAN9=/usr/lib/plan9

  - if [ ! -f "$CGD" ]; then
  -   apt install -y golang
  -   mkdir -p ./cgd
  -   GOPATH=$(realpath ./cgd) go install github.com/uriel/cgd@latest
  - fi

  - if [ ! -d "$WERC" ]; then
  -   wget http://code.9front.org/hg/werc/archive/tip.tar.gz -O - | tar xz
  -   mv ./werc-* $WERC
  - fi

  - for bin in rc awk; do
  -   rm -f /bin/$bin && ln -s $PLAN9/bin/$bin /bin/$bin
  - done

pages:
  script:
    - rm -rf $WERC/sites/localhost
    - cp -r ./docs $WERC/sites/localhost

    - $CGD -c $WERC/bin/werc.rc -w $WERC/bin -a localhost:80 &
    - 'wget --retry-connrefused -r -k -e robots=off http://localhost 2> /dev/null || echo wget exited: $?'
    - jobs -p | xargs kill

    - rm -rf ./public
    - mv ./localhost public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "main"

  environment: production
