image: node:lts

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

pages:
  script:
    - yarn prep_listing && yarn build
    - cp -prn ./out/* ./public

  artifacts:
    paths:
      - public

  rules:
    - if: $CI_COMMIT_BRANCH == "main"

  environment: production
